---
title: "**Kalem Hanlon**"
date: "2024-09-06"
output: pdf_document
---
kh832@cornell.edu

## Profole
First year masters student studying nutrition with a focus on molecular nutrition. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Previous Lab Experience:
<br> 
**Position in Dr. Geuking’s Laboratory – University of Calgary**  
Summer position working with genetically modified bacteria in germ free mice and subsequent immunological implications.  
05/2023–08/2023

<br>

**Undergraduate thesis in the Renwick laboratory – Queen’s University**     
Completed immunohistochemistry staining and chromogenic in-situ hybridization on various clinical tissue samples to determine diagnostic protein and RNA expression in neuroendocrine tumours.  
09/2023-04/2024

## Education
**Queen’s University — Life Sciences Specialization - Biomedical Sciences	Class of 2024**  

GPA: 4.28 | Dean’s Honour’s List with Distinction; 21’, 22’, 23’

<br>

Queen’s University Excellence Scholarship
AMHL Academic Scholarship | CRAA ED Melville Scholarship

<br>

James H. Rattray Scholarship in Science: 22’, 23’, 24’

<br>

Dean’s award of excellence: 23’

<br>

Recipient of Alberta Innovates Summer Research Studentship 2023

<br>

Nan Skelding Scholarship | Undergraduate prize in Microbiology

<br>

Pathology and Molecular Medicine Undergraduate Research Prize
	


